version: '3.8'

services:
  face-detection:
    build: .
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
      - ./known_faces:/app/known_faces
    restart: unless-stopped
    networks:
      - face-net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  # Use port 8080 instead of 80
      - "8443:443" # Use port 8443 instead of 443
    volumes:
      - ./nginx-custom-port.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
    depends_on:
      - face-detection
    restart: unless-stopped
    networks:
      - face-net

networks:
  face-net:
    driver: bridge