version: '3.8'

services:
  face-detection:
    build: .
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
      - ./known_faces:/app/known_faces
    restart: unless-stopped
    networks:
      - face-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - face-detection
    restart: unless-stopped
    networks:
      - face-net

networks:
  face-net:
    driver: bridge